# name: k8smanifest.yaml
# description: deploys application into sandbox namespace and exposes on an Azure internal load balancer
# author: Nigel Wardle
# created: 05/11/19
# modified 05/11/19 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  namespace: sandbox
  labels:
    app: phpapp1
    env: dev
    tier: monolith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpapp1
  template:
    metadata:
      labels:
        app: phpapp1
        env: dev
        tier: monolith
    spec:
      containers:
      - name: webapp1
        image: cdwuk/php-app:latest
        resources: 
          requests:
            memory: "250Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: php-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
    # service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "apps-subnet"
spec:
  type: LoadBalancer
  #   loadBalancerIP: 10.240.0.25
  ports:
  - port: 80
  selector:
    app: phpapp1
