# name: go-kube-manifest.yaml
# description: deploys application into sandbox namespace and exposes on an Azure internal load balancer
# author: Nigel Wardle
# created: 05/11/19
# modified 05/11/19 
# *******************************************
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go
  labels:
    app: go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - name: go
        image: cdwuk/go-app:latest
#        resources: 
 #       requests:
 #        memory: "2000Mi"
 #        cpu: "2000m"
 #      limits:
 #       memory: "2500Mi"
 #      cpu: "2500m"
        ports:
        - containerPort: 8080
---
# expose pods to service on public IP
apiVersion: v1
kind: Service
metadata:
  name: go
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false" # set to true for public IP
    # service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "apps-subnet" # specify subnet
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: go
