# name: k8smanifest.yaml
# description: deploys application into sandbox namespace and exposes on an Azure internal load balancer
# author: Nigel Wardle
# created: 05/11/19
# modified 05/11/19 
# *******************************************

apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-standard
  labels:
    app: python-standard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-standard
  template:
    metadata:
      labels:
        app: python-standard
    spec:
      containers:
      - name: python-standard
        image: cdwuk/python-standard:v1.0.0
        resources: 
          requests:
            memory: "2000Mi"
            cpu: "2000m"
          limits:
            memory: "2500Mi"
            cpu: "2500m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: python-standard
spec:
  type: NodePort
  ports:
  - port: 50002
  selector:
    app: python-standard
